raw_symbols = r"[-0-9a-zA-Zа-яА-ЯёЁ\s_{}!#?$%&='*\[\]+.^{}()`⚡|~@:;/\\]"
cyrillic_modifiers = {
    'Налетчик': 'Raider',
    'Владение луком': 'Bow Mastery',
    'Ловкий солдат': 'Agile Soldier',
    'Опа! Монетка!': 'Look! A coin!',
    'Природный дар': 'Natural Talent',
    'Владение мечом': 'Sword Mastery',
    'Владение броней': 'Armor Mastery',
    'Владение копьем': 'Spear Mastery',
    'Владение щитом': 'Shield Mastery',
    'Критический удар!': 'Critical hit!',
    'Владение кинжалом': 'Dagger Mastery',
    'Все, что блестит': 'All That Glitters',
    'Мастер второй руки': 'Off-Hand Mastery',
    'Удачливый защитник!': 'Lucky Defender!',
    'Одаренный следопыт': 'Gifted Pathfinder',
    'Стойкий щитоносец': 'Enduring Shieldbearer',
    'Владение дробящим оружием': 'Blunt Mastery',
    'Владение легкой броней': 'Light Armor Mastery',
    'Качай мышцы, а не мозги': 'Muscles, not Brains',
    'Владение тяжелой броней': 'Heavy Armor Mastery',
    'Владение магической броней': 'Robe Armor Mastery',
    'Владение боевыми зельями': 'Combat Potions Mastery',
}
