cw = 'cw3'
if cw == 'cw2':
    token = '530805773:AAFE-VDtmvxtCfJAzsTMTNBT74VWxDFguj4'
    server = 1
    file = 'eustorage'
    json_old = 'eustorage1.json'
    json_storage = 'eustorage2.json'
    adress = 'https://t.me/ChatWarsAuction/'
    actual = 7
    # ---------------------- forms ----------------------
    title = 'Lot #(\d+) : (.*)'
    quali = 'Quality: (.*)'
    condi = 'Condition: (.*)'
    seller = 'Seller: (.*)'
    price = 'Current price: (\d+) pouch\(es\)'
    buys = 'Buyer: (.+)'
    stamp = 'End At: (\d{2}) (.*) 10(\d{2}) (\d{2}):(\d{2})'
    status = 'Status: (#active|Finished|Cancelled|Failed)'
    # -------------------- statistic --------------------
    lastsold = 'Last sold: '
    soldtimes = '<b>Times sold: </b>'
    alltime = '<b>All time:</b>'
    days = '<b>Last 7 days:</b>'
    median = 'Median: '
    average = 'Average: '
    minmax = 'Min/Max: '
    unsold = 'Unsold: '
    lot = 'Lot'
else:
    token = '468445195:AAHKJxXQRxg5kJau_KT4smoCvJfnqcgOS4c'
    server = 2
    file = 'storage'
    json_old = 'bigdata1.json'
    json_storage = 'bigdata2.json'
    adress = 'https://t.me/chatwars3/'
    actual = 8
    # ---------------------- forms ----------------------
    title = 'Лот #(\d+) : (.*)'
    quali = 'Качество: (.*)'
    condi = 'Состояние: (.*)'
    seller = 'Продавец: (.*)'
    price = 'Текущая .*: (\d+) 👝'
    buys = 'Покупатель: (.+)'
    stamp = 'Срок: (\d{2}) (.*) 10(\d{2}) (\d{2}):(\d{2})'
    status = 'Статус: (#active|Finished|Cancelled|Failed)'
    # -------------------- statistic --------------------
    lastsold = 'Последний проданный: '
    soldtimes = '<b>Продано раз: </b>'
    alltime = '<b>За всё время:</b>'
    days = '<b>За последние 7 дней:</b>'
    median = 'Медианная цена: '
    average = 'Средняя цена: '
    minmax = 'Мин/Макс: '
    unsold = 'Не продано: '
    lot = 'Лот'
